package Supplier;

import User.Login;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giaba
 */
public class SupplierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SupplierDashboard
     */
    Color selectionColor = new Color(34, 48, 62);
    Color textSelectionColor = new Color(255, 255, 255);
    int xx, xy;
    public SupplierDashboard() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplierEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelAccount = new javax.swing.JPanel();
        accountlb = new javax.swing.JLabel();
        iconAccountDark = new javax.swing.JLabel();
        iconAccountLight = new javax.swing.JLabel();
        PanelDelivery = new javax.swing.JPanel();
        deliverylb = new javax.swing.JLabel();
        iconDeliveryDark = new javax.swing.JLabel();
        iconDeliveryLight = new javax.swing.JLabel();
        PanelDeliveries = new javax.swing.JPanel();
        deliverieslb = new javax.swing.JLabel();
        iconDeliveriesDark = new javax.swing.JLabel();
        iconDeliveriesLight = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stDel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bookstore.png"))); // NOI18N
        jLabel1.setText("BOOK SHOP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel2.setText("Đăng xuất");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        supplierEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        supplierEmail.setForeground(new java.awt.Color(255, 255, 255));
        supplierEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        supplierEmail.setText("supplier@gmail.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(supplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supplierEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

        jPanel3.setBackground(new java.awt.Color(42, 58, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard.png"))); // NOI18N
        jLabel4.setText("Trang chủ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 50));

        PanelAccount.setBackground(new java.awt.Color(42, 58, 73));
        PanelAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountlb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountlb.setForeground(new java.awt.Color(102, 120, 138));
        accountlb.setText("Tài khoản của tôi");
        accountlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountlbMouseClicked(evt);
            }
        });
        PanelAccount.add(accountlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconAccountDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/account_dark.png"))); // NOI18N
        PanelAccount.add(iconAccountDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconAccountLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/account_light.png"))); // NOI18N
        PanelAccount.add(iconAccountLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 30));

        PanelDelivery.setBackground(new java.awt.Color(42, 58, 73));
        PanelDelivery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliverylb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deliverylb.setForeground(new java.awt.Color(102, 120, 138));
        deliverylb.setText("    Vận chuyển");
        deliverylb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliverylbMouseClicked(evt);
            }
        });
        PanelDelivery.add(deliverylb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 30));

        iconDeliveryDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delivery_dark.png"))); // NOI18N
        PanelDelivery.add(iconDeliveryDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconDeliveryLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delivery_light.png"))); // NOI18N
        PanelDelivery.add(iconDeliveryLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 30));

        PanelDeliveries.setBackground(new java.awt.Color(42, 58, 73));
        PanelDeliveries.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliverieslb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deliverieslb.setForeground(new java.awt.Color(102, 120, 138));
        deliverieslb.setText("Giao hàng");
        deliverieslb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliverieslbMouseClicked(evt);
            }
        });
        PanelDeliveries.add(deliverieslb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconDeliveriesDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchasedetails_dark.png"))); // NOI18N
        PanelDeliveries.add(iconDeliveriesDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconDeliveriesLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchasedetails_light.png"))); // NOI18N
        PanelDeliveries.add(iconDeliveriesLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelDeliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 650));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Số liệu thống kê");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Chuyến giao hàng của tôi");

        stDel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stDel.setForeground(new java.awt.Color(51, 51, 51));
        stDel.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(stDel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stDel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 400, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        icons();
    }

    private void icons() {
        iconDeliveryDark.setVisible(true);
        iconDeliveryLight.setVisible(false);
        iconDeliveriesDark.setVisible(true);
        iconDeliveriesLight.setVisible(false);
        iconAccountDark.setVisible(true);
        iconAccountLight.setVisible(false);

    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất bây giờ không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new Login().setVisible(true);//tro ve trang dang nhap
            this.dispose();//Khi nhấn vào dấu x thì sẽ thoát khỏi chương trình
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void deliverylbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverylbMouseClicked
        PanelDelivery.setBackground(selectionColor);
        deliverylb.setForeground(textSelectionColor);
        iconDeliveryDark.setVisible(false);
        iconDeliveryLight.setVisible(true);
        Delivery delivery = new Delivery();
        delivery.setVisible(true);
        delivery.pack();
    }//GEN-LAST:event_deliverylbMouseClicked

    private void deliverieslbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliverieslbMouseClicked
        PanelDeliveries.setBackground(selectionColor);
        deliverieslb.setForeground(textSelectionColor);
        iconDeliveriesDark.setVisible(false);
        iconDeliveriesLight.setVisible(true);
        MyDeliveries myDeliveries = new MyDeliveries();
        myDeliveries.setVisible(true);
        myDeliveries.pack();
    }//GEN-LAST:event_deliverieslbMouseClicked

    private void accountlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountlbMouseClicked
        PanelAccount.setBackground(selectionColor);
        accountlb.setForeground(textSelectionColor);
        iconAccountDark.setVisible(false);
        iconAccountLight.setVisible(true);
        SupplierAccount supplierAccount = new SupplierAccount();
        supplierAccount.setVisible(true);
        supplierAccount.pack();
    }//GEN-LAST:event_accountlbMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i <= 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {

                Thread.sleep(40);
            } catch (InterruptedException ex) {
                Logger.getLogger(SupplierDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       xx = evt.getX();
        xy = evt.getY();// 2 cái trên làm di chuyển được trang  
    }//GEN-LAST:event_jPanel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelAccount;
    public static javax.swing.JPanel PanelDeliveries;
    public static javax.swing.JPanel PanelDelivery;
    public static javax.swing.JLabel accountlb;
    public static javax.swing.JLabel deliverieslb;
    public static javax.swing.JLabel deliverylb;
    public static javax.swing.JLabel iconAccountDark;
    public static javax.swing.JLabel iconAccountLight;
    public static javax.swing.JLabel iconDeliveriesDark;
    public static javax.swing.JLabel iconDeliveriesLight;
    public static javax.swing.JLabel iconDeliveryDark;
    public static javax.swing.JLabel iconDeliveryLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JLabel stDel;
    public static javax.swing.JLabel supplierEmail;
    // End of variables declaration//GEN-END:variables
}
