package User;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giaba
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    Color selectionColor = new Color(34, 48, 62);
    Color textSelectionColor = new Color(255, 255, 255);
    int xx, xy;

    public UserDashboard() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelMyAccount = new javax.swing.JPanel();
        MyAccountlb = new javax.swing.JLabel();
        iconAccountDark = new javax.swing.JLabel();
        iconAccountLight = new javax.swing.JLabel();
        PanelPurchase = new javax.swing.JPanel();
        purchaselb = new javax.swing.JLabel();
        iconPurchaseDark = new javax.swing.JLabel();
        iconPurchaseLight = new javax.swing.JLabel();
        PanelPurchaseDetails = new javax.swing.JPanel();
        purchaseDetailslb = new javax.swing.JLabel();
        iconDetailsDark = new javax.swing.JLabel();
        iconDetailsLight = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stCat = new javax.swing.JLabel();
        stPro = new javax.swing.JLabel();
        stPur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bookstore.png"))); // NOI18N
        jLabel1.setText("BOOK SHOP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel2.setText("Đăng xuất");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 255, 255));
        userEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        userEmail.setText("user@gmail.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

        jPanel3.setBackground(new java.awt.Color(42, 58, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard.png"))); // NOI18N
        jLabel4.setText("Trang chủ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 50));

        PanelMyAccount.setBackground(new java.awt.Color(42, 58, 73));
        PanelMyAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MyAccountlb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MyAccountlb.setForeground(new java.awt.Color(102, 120, 138));
        MyAccountlb.setText("Tài khoản của tôi");
        MyAccountlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAccountlbMouseClicked(evt);
            }
        });
        PanelMyAccount.add(MyAccountlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconAccountDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/account_dark.png"))); // NOI18N
        PanelMyAccount.add(iconAccountDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconAccountLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/account_light.png"))); // NOI18N
        PanelMyAccount.add(iconAccountLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelMyAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 30));

        PanelPurchase.setBackground(new java.awt.Color(42, 58, 73));
        PanelPurchase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchaselb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        purchaselb.setForeground(new java.awt.Color(102, 120, 138));
        purchaselb.setText("     Mua sách");
        purchaselb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaselbMouseClicked(evt);
            }
        });
        PanelPurchase.add(purchaselb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 30));

        iconPurchaseDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchase_dark.png"))); // NOI18N
        PanelPurchase.add(iconPurchaseDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconPurchaseLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchase_light.png"))); // NOI18N
        PanelPurchase.add(iconPurchaseLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 30));

        PanelPurchaseDetails.setBackground(new java.awt.Color(42, 58, 73));
        PanelPurchaseDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchaseDetailslb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        purchaseDetailslb.setForeground(new java.awt.Color(102, 120, 138));
        purchaseDetailslb.setText("Chi tiết mua hàng");
        purchaseDetailslb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseDetailslbMouseClicked(evt);
            }
        });
        PanelPurchaseDetails.add(purchaseDetailslb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconDetailsDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchasedetails_dark.png"))); // NOI18N
        PanelPurchaseDetails.add(iconDetailsDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconDetailsLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/purchasedetails_light.png"))); // NOI18N
        PanelPurchaseDetails.add(iconDetailsLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelPurchaseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 650));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Số liệu thống kê");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Tổng số thể loại:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Tổng số sách:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Tổng số tiền mua:");

        stCat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stCat.setForeground(new java.awt.Color(51, 51, 51));
        stCat.setText("0");

        stPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stPro.setForeground(new java.awt.Color(51, 51, 51));
        stPro.setText("0");

        stPur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stPur.setForeground(new java.awt.Color(51, 51, 51));
        stPur.setText("0.0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(stCat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(80, 80, 80)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stPur, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(stCat)
                    .addComponent(stPur))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stPro))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 980, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        icons();
    }

    private void icons() {
        iconPurchaseDark.setVisible(true);
        iconPurchaseLight.setVisible(false);
        iconDetailsDark.setVisible(true);
        iconDetailsLight.setVisible(false);
        iconAccountDark.setVisible(true);
        iconAccountLight.setVisible(false);

    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất bây giờ không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new Login().setVisible(true);//tro ve trang dang nhap
            this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void purchaselbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaselbMouseClicked
        PanelPurchase.setBackground(selectionColor);
        purchaselb.setForeground(textSelectionColor);
        iconPurchaseDark.setVisible(false);
        iconPurchaseLight.setVisible(true);
        Purchase purchase = new Purchase();
        purchase.setVisible(true);
        purchase.pack();
    }//GEN-LAST:event_purchaselbMouseClicked

    private void purchaseDetailslbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseDetailslbMouseClicked
        PanelPurchaseDetails.setBackground(selectionColor);
        purchaseDetailslb.setForeground(textSelectionColor);
        iconDetailsDark.setVisible(false);
        iconDetailsLight.setVisible(true);
        PurchaseDetails purchaseDetails = new PurchaseDetails();
        purchaseDetails.setVisible(true);
        purchaseDetails.pack();
    }//GEN-LAST:event_purchaseDetailslbMouseClicked

    private void MyAccountlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountlbMouseClicked
        PanelMyAccount.setBackground(selectionColor);
        MyAccountlb.setForeground(textSelectionColor);
        iconAccountDark.setVisible(false);
        iconAccountLight.setVisible(true);
        UserAccount userAccount = new UserAccount();
        userAccount.setVisible(true);
        userAccount.pack();
    }//GEN-LAST:event_MyAccountlbMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i <= 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {

                Thread.sleep(40);
            } catch (InterruptedException ex) {
                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();// 2 cái trên làm di chuyển được trang  
    }//GEN-LAST:event_jPanel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel MyAccountlb;
    public static javax.swing.JPanel PanelMyAccount;
    public static javax.swing.JPanel PanelPurchase;
    public static javax.swing.JPanel PanelPurchaseDetails;
    public static javax.swing.JLabel iconAccountDark;
    public static javax.swing.JLabel iconAccountLight;
    public static javax.swing.JLabel iconDetailsDark;
    public static javax.swing.JLabel iconDetailsLight;
    public static javax.swing.JLabel iconPurchaseDark;
    public static javax.swing.JLabel iconPurchaseLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JLabel purchaseDetailslb;
    public static javax.swing.JLabel purchaselb;
    public static javax.swing.JLabel stCat;
    public static javax.swing.JLabel stPro;
    public static javax.swing.JLabel stPur;
    public static javax.swing.JLabel userEmail;
    // End of variables declaration//GEN-END:variables
}
