package Admin;

import User.Login;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giaba
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    Color selectionColor = new Color(34, 48, 62);
    Color textSelectionColor = new Color(255, 255, 255);
int xx, xy;
    public AdminDashboard() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelTransaction = new javax.swing.JPanel();
        transaction = new javax.swing.JLabel();
        iconTransactionDark = new javax.swing.JLabel();
        iconTransactionLight = new javax.swing.JLabel();
        PanelManageCategory = new javax.swing.JPanel();
        manageCategory = new javax.swing.JLabel();
        iconCategorydark = new javax.swing.JLabel();
        iconCategorylight = new javax.swing.JLabel();
        PanelManageProduct = new javax.swing.JPanel();
        manageProduct = new javax.swing.JLabel();
        iconProductDark = new javax.swing.JLabel();
        iconProductLight = new javax.swing.JLabel();
        PanelManageUser = new javax.swing.JPanel();
        manageUser = new javax.swing.JLabel();
        iconUserDark = new javax.swing.JLabel();
        iconUserLight = new javax.swing.JLabel();
        PanelAddSupplier = new javax.swing.JPanel();
        addSupplier = new javax.swing.JLabel();
        iconSupplierDark = new javax.swing.JLabel();
        iconSupplierLight = new javax.swing.JLabel();
        PanelManageSupplier = new javax.swing.JPanel();
        ManageSupplier = new javax.swing.JLabel();
        iconManageSuppierDark = new javax.swing.JLabel();
        iconManageSuppierLight = new javax.swing.JLabel();
        PanelSelectionSupplier = new javax.swing.JPanel();
        selectionSupplier = new javax.swing.JLabel();
        iconSelectSupplierDark = new javax.swing.JLabel();
        iconSelectSupplierLight = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stCat = new javax.swing.JLabel();
        stPro = new javax.swing.JLabel();
        stUser = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        stSupplier = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        stTSales = new javax.swing.JLabel();
        stSales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bookstore.png"))); // NOI18N
        jLabel1.setText("BOOK SHOP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel2.setText("Đăng xuất");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        adminEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminEmail.setForeground(new java.awt.Color(255, 255, 255));
        adminEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        adminEmail.setText("admin@gmail.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(adminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

        jPanel3.setBackground(new java.awt.Color(42, 58, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard.png"))); // NOI18N
        jLabel4.setText("Trang chủ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 50));

        PanelTransaction.setBackground(new java.awt.Color(42, 58, 73));
        PanelTransaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transaction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transaction.setForeground(new java.awt.Color(102, 120, 138));
        transaction.setText("Giao dịch");
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
        });
        PanelTransaction.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconTransactionDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/transaction_dark.png"))); // NOI18N
        PanelTransaction.add(iconTransactionDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconTransactionLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/transaction_light.png"))); // NOI18N
        PanelTransaction.add(iconTransactionLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 30));

        PanelManageCategory.setBackground(new java.awt.Color(42, 58, 73));
        PanelManageCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageCategory.setForeground(new java.awt.Color(102, 120, 138));
        manageCategory.setText("    Quản lý thể loại");
        manageCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCategoryMouseClicked(evt);
            }
        });
        PanelManageCategory.add(manageCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 30));

        iconCategorydark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/category_dark.png"))); // NOI18N
        PanelManageCategory.add(iconCategorydark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconCategorylight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/category_light.png"))); // NOI18N
        PanelManageCategory.add(iconCategorylight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelManageCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 30));

        PanelManageProduct.setBackground(new java.awt.Color(42, 58, 73));
        PanelManageProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageProduct.setForeground(new java.awt.Color(102, 120, 138));
        manageProduct.setText("Quản lý sản phẩm");
        manageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageProductMouseClicked(evt);
            }
        });
        PanelManageProduct.add(manageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconProductDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/product_dark.png"))); // NOI18N
        PanelManageProduct.add(iconProductDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconProductLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/product_light.png"))); // NOI18N
        PanelManageProduct.add(iconProductLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelManageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 30));

        PanelManageUser.setBackground(new java.awt.Color(42, 58, 73));
        PanelManageUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageUser.setForeground(new java.awt.Color(102, 120, 138));
        manageUser.setText("Quản lý người dùng");
        manageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserMouseClicked(evt);
            }
        });
        PanelManageUser.add(manageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconUserDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_dark.png"))); // NOI18N
        PanelManageUser.add(iconUserDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconUserLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_user.png"))); // NOI18N
        PanelManageUser.add(iconUserLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 30));

        PanelAddSupplier.setBackground(new java.awt.Color(42, 58, 73));
        PanelAddSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addSupplier.setForeground(new java.awt.Color(102, 120, 138));
        addSupplier.setText("Thêm nhà cung cấp");
        addSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSupplierMouseClicked(evt);
            }
        });
        PanelAddSupplier.add(addSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconSupplierDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier_dark.png"))); // NOI18N
        PanelAddSupplier.add(iconSupplierDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconSupplierLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier_light.png"))); // NOI18N
        PanelAddSupplier.add(iconSupplierLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelAddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 30));

        PanelManageSupplier.setBackground(new java.awt.Color(42, 58, 73));
        PanelManageSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageSupplier.setForeground(new java.awt.Color(102, 120, 138));
        ManageSupplier.setText("Quản lý nhà cung cấp");
        ManageSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageSupplierMouseClicked(evt);
            }
        });
        PanelManageSupplier.add(ManageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconManageSuppierDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_supplier_dark.png"))); // NOI18N
        PanelManageSupplier.add(iconManageSuppierDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconManageSuppierLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_supplier_light.png"))); // NOI18N
        PanelManageSupplier.add(iconManageSuppierLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelManageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 30));

        PanelSelectionSupplier.setBackground(new java.awt.Color(42, 58, 73));
        PanelSelectionSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectionSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        selectionSupplier.setForeground(new java.awt.Color(102, 120, 138));
        selectionSupplier.setText("Chọn nhà cung cấp");
        selectionSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectionSupplierMouseClicked(evt);
            }
        });
        PanelSelectionSupplier.add(selectionSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        iconSelectSupplierDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier_dark.png"))); // NOI18N
        PanelSelectionSupplier.add(iconSelectSupplierDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        iconSelectSupplierLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier_light.png"))); // NOI18N
        PanelSelectionSupplier.add(iconSelectSupplierLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 30, 31));

        jPanel3.add(PanelSelectionSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 650));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Số liệu thống kê");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Tổng số thể loại:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Tổng số sách:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Tổng người dùng:");

        stCat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stCat.setForeground(new java.awt.Color(51, 51, 51));
        stCat.setText("0");

        stPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stPro.setForeground(new java.awt.Color(51, 51, 51));
        stPro.setText("0");

        stUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stUser.setForeground(new java.awt.Color(51, 51, 51));
        stUser.setText("0");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Doanh thu hôm nay:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Tổng nhà cung cấp:");

        stSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stSupplier.setForeground(new java.awt.Color(51, 51, 51));
        stSupplier.setText("0");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Tổng doanh thu:");

        stTSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stTSales.setForeground(new java.awt.Color(51, 51, 51));
        stTSales.setText("0.0");

        stSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stSales.setForeground(new java.awt.Color(51, 51, 51));
        stSales.setText("0.0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stPro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(stCat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stUser, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stTSales, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stSales, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(stCat)
                    .addComponent(stUser)
                    .addComponent(jLabel23)
                    .addComponent(stTSales))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stPro)
                    .addComponent(jLabel24)
                    .addComponent(stSupplier)
                    .addComponent(jLabel26)
                    .addComponent(stSales))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 980, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        icons();
    }
// Khi nhấn vào icon thì sẽ sáng lên

    private void icons() {
        iconCategorydark.setVisible(true);
        iconCategorylight.setVisible(false);
        iconProductDark.setVisible(true);
        iconProductLight.setVisible(false);
        iconUserDark.setVisible(true);
        iconUserLight.setVisible(false);
        iconSupplierDark.setVisible(true);
        iconSupplierLight.setVisible(false);
        iconManageSuppierDark.setVisible(true);
        iconManageSuppierLight.setVisible(false);
        iconSelectSupplierDark.setVisible(true);
        iconSelectSupplierLight.setVisible(false);
        iconTransactionDark.setVisible(true);
        iconTransactionLight.setVisible(false);

    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất bây giờ không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new Login().setVisible(true);//tro ve trang dang nhap
            this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked
// Khi click vào thì chữ sáng
    private void manageCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCategoryMouseClicked
        PanelManageCategory.setBackground(selectionColor);
        manageCategory.setForeground(textSelectionColor);
        iconCategorydark.setVisible(false);
        iconCategorylight.setVisible(true);
        ManageCategory manageCategory = new ManageCategory();
        manageCategory.setVisible(true);
        manageCategory.pack();
    }//GEN-LAST:event_manageCategoryMouseClicked

    private void manageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProductMouseClicked
        PanelManageProduct.setBackground(selectionColor);
        manageProduct.setForeground(textSelectionColor);
        iconProductDark.setVisible(false);
        iconProductLight.setVisible(true);
        ManageProduct manageProduct = new ManageProduct();
        manageProduct.setVisible(true);
        manageProduct.pack();
    }//GEN-LAST:event_manageProductMouseClicked

    private void manageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseClicked
        PanelManageUser.setBackground(selectionColor);
        manageUser.setForeground(textSelectionColor);
        iconUserDark.setVisible(false);
        iconUserLight.setVisible(true);
        ManageUser manageUsers = new ManageUser();
        manageUsers.setVisible(true);
        manageUsers.pack();

    }//GEN-LAST:event_manageUserMouseClicked

    private void addSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSupplierMouseClicked
        PanelAddSupplier.setBackground(selectionColor);
        addSupplier.setForeground(textSelectionColor);
        iconSupplierDark.setVisible(false);
        iconSupplierLight.setVisible(true);
        AddSupplier addSuppliers = new AddSupplier();
        addSuppliers.setVisible(true);
        addSuppliers.pack();
    }//GEN-LAST:event_addSupplierMouseClicked

    private void ManageSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSupplierMouseClicked
        PanelManageSupplier.setBackground(selectionColor);
        ManageSupplier.setForeground(textSelectionColor);
        iconManageSuppierDark.setVisible(false);
        iconManageSuppierLight.setVisible(true);
        ManageSuppliers manageSuppliers = new ManageSuppliers();
        manageSuppliers.setVisible(true);
        manageSuppliers.pack();
    }//GEN-LAST:event_ManageSupplierMouseClicked

    private void selectionSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionSupplierMouseClicked
        PanelSelectionSupplier.setBackground(selectionColor);
        selectionSupplier.setForeground(textSelectionColor);
        iconSelectSupplierDark.setVisible(false);
        iconSelectSupplierLight.setVisible(true);
        SelectSupplier selectSuppliers = new SelectSupplier();
        selectSuppliers.setVisible(true);
        selectSuppliers.pack();
    }//GEN-LAST:event_selectionSupplierMouseClicked

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked
        PanelTransaction.setBackground(selectionColor);
        transaction.setForeground(textSelectionColor);
        iconTransactionDark.setVisible(false);
        iconTransactionLight.setVisible(true);
        Transaction transactions = new Transaction();
        transactions.setVisible(true);
        transactions.pack();
    }//GEN-LAST:event_transactionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i <= 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {

                Thread.sleep(40);
            } catch (InterruptedException ex) {
                Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();// 2 cái trên làm di chuyển được trang  
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ManageSupplier;
    public static javax.swing.JPanel PanelAddSupplier;
    public static javax.swing.JPanel PanelManageCategory;
    public static javax.swing.JPanel PanelManageProduct;
    public static javax.swing.JPanel PanelManageSupplier;
    public static javax.swing.JPanel PanelManageUser;
    public static javax.swing.JPanel PanelSelectionSupplier;
    public static javax.swing.JPanel PanelTransaction;
    public static javax.swing.JLabel addSupplier;
    public static javax.swing.JLabel adminEmail;
    public static javax.swing.JLabel iconCategorydark;
    public static javax.swing.JLabel iconCategorylight;
    public static javax.swing.JLabel iconManageSuppierDark;
    public static javax.swing.JLabel iconManageSuppierLight;
    public static javax.swing.JLabel iconProductDark;
    public static javax.swing.JLabel iconProductLight;
    public static javax.swing.JLabel iconSelectSupplierDark;
    public static javax.swing.JLabel iconSelectSupplierLight;
    public static javax.swing.JLabel iconSupplierDark;
    public static javax.swing.JLabel iconSupplierLight;
    public static javax.swing.JLabel iconTransactionDark;
    public static javax.swing.JLabel iconTransactionLight;
    public static javax.swing.JLabel iconUserDark;
    public static javax.swing.JLabel iconUserLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JLabel manageCategory;
    public static javax.swing.JLabel manageProduct;
    public static javax.swing.JLabel manageUser;
    public static javax.swing.JLabel selectionSupplier;
    public static javax.swing.JLabel stCat;
    public static javax.swing.JLabel stPro;
    public static javax.swing.JLabel stSales;
    public static javax.swing.JLabel stSupplier;
    public static javax.swing.JLabel stTSales;
    public static javax.swing.JLabel stUser;
    public static javax.swing.JLabel transaction;
    // End of variables declaration//GEN-END:variables
}
